### PR TITLE
Resolve issues with making reform Calculator

### PR DESCRIPTION
**Pull request by talumbau**
- implement_reform doesn't mutate current_year
- filter out empty mod dictionaries
- restore test that dropq depends on

### CODE REVIEW

**Comment by MattHJensen** [comment]
@martinholmer, fyi, you are the only person who can merge this. Seems like there are two paths forward:

1. @martinholmer could merge this so we can move on with https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/343; then, once we have some usage examples later on, we can discuss whether it is more intuitive to change the current year to the start year via `implement_reform`, at which point we can refactor dropq as needed. 
2. we could all hop on a call to discuss whether there is a urgent reason to change current year to start year via `implement_reform` as part of this PR, in which case we would also need to refactor drop q now. 

I have a slight preference towards (1) since it seems a bit easier (although the drop q refactor doesn't seem so hard), but perhaps preference towards (1) is just because I don't yet see the what would be illuminated on a call.

**Comment by martinholmer** [comment]
T.J. @talumbau and @MattHJensen,

I've given T.J.'s pull request (that would modify my PR#343) some thought, but I don't think it gets at the heart of the matter.  The solution that I proposed was to use the redesigned Parameters class in the dropq.run_models code in place of the calculator factory function.  When I posted the code changes that allow run_models to execute correctly, I didn't understand how **severely flawed** the calculator factory function is on the master branch.  I'll explain below why I now think that, but the implication of this revelation for me is that we should take PR#343 as an opportunity to completely remove the calculator factory function from both the Tax-Calculator repo (where it is used only in tests) and the dropQ repo (where it is used only twice).  There is nothing to do in the webapp repo because the calculator factory function does not seem to be used there.  Notice that T.J.'s focus has been on preserving the calculator factory function, arguing that it is working just fine on the master branch.  My tests below suggest that on the master branch the calculator factory function does not work correctly and certainly does not support the kind of real-world tax policy reforms that people will want to specify.

Let me take just a moment to ensure that we all understand what I mean by  "real-world tax policy reforms".  Currently the webapp produces results for ten years beginning with 2015.  The vast majority of reforms that people are going to be interested in analyzing involve changing tax policy parameters in years after 2015.  Why?  There are at least two reasons.  First, many reforms call for a gradual phasing-in of changes (say with the first change in 2015 and the last change in 2018).  Second, most tax analysts want the ability to analyze a reform that begins in a year or two from now because they know that the political discussion and legislative process will take that long for the reform to be implemented.

Now that I have downloaded the dropQ code, I can see that the calculator factory function cannot be used to specify reforms that have any tax policy parameter changes after 2015.  I noticed this by looking at example.py (which seems to be the closest thing to a test of the code in dropq.py as there is).  Here are the parts of that script (from the master branch) that specify the reform and call dropq.run_models:
```
myvars = {}
myvars['_II_rt4'] = [0.39]
user_mods = {2015: myvars}
...
mY_dec, ..., fiscal_tots = dropq.run_models(tax_dta, num_years=10, user_mods=user_mods)
```
What I did to simulate a real-world tax reform was to change user_mods to be this:
```
user_mods = {2016: myvars}
```
After making that single code change, executing the example.py script produces the following:
```
iMac2:dropQ-master mrh$ python example.py 
You loaded data for 2008.
Your data have beeen extrapolated to 2013.
You loaded data for 2008.
Your data have beeen extrapolated to 2013.
Modifications are for year 2016 and Parameters are for year 2013. Parameters will be advanced to year 2016
Modifications are for year 2016 and Records are for year 2008. Records will be advanced to year 2016
Traceback (most recent call last):
  File "example.py", line 20, in <module>
    mY_dec, mX_dec, df_dec, mY_bin, mX_bin, df_bin, fiscal_tots = dropq.run_models(tax_dta, num_years=10, user_mods=user_mods)
  File "/Users/mrh/work/OSPC/dropQ-master/dropq/dropq.py", line 333, in run_models
    assert calc3.current_year == start_year
AssertionError
```
I am suggesting the elimination of the calculator factory function because its limitations (on the master branch) are so severe and because there is now an alternative in PR#343 that does allow realistic reforms to the specified.  I am leaving early Saturday morning for nearly a week in Canada and will be back in the office on Friday, September 11.  That leaves plenty of time for T.J. to eliminate the two calls to the calculator factory function in the dropQ repo.  And then when I'm back I can remove the calculator factory function from the Tax-Calculator repo.

Does this make sense as a course of action, or am I missing something?

**Comment by talumbau** [comment]
Hi Martin,

I don't understand your claims about the `calculator` function and your example shows desired behavior. The assertion violation you got is correct. `example.py` is a simple way of running dropq in the way that is done for the web application. In particular, we expect input from the user only for the year 2015. If somehow the web application was modified to provide a reform starting in 2016, and there were not concurrent changes made to dropq, this should be considered an error because it is unexpected input and it would be bad if the code did not raise an exception or trip an assertion.

In particular, the `run_models` function has a `start_year` argument which currently defaults to 2015. So, one necessary change would be to call `run_models` with the keyword argument 2016. Also, the two 'default' Calculator instances are hard-coded to advance only to 2015. The third calculator instance, though, because of the factory function, will automatically advance to the year given in the user modification dictionary, which would be 2016. This exact example shows why it's useful to have such a function, because one doesn't have to go and modify the code that creates a Calculator instance when one changes the year in a user_mods dictionary. So, I would say I'm very confused at what you have written, and it does seem that you have missed the intention of the assertion statements.

The additional expenditure of time happens not at the present time as we are going through your PR, but at the conclusion of these activities when we will have, presumably, a PR on Tax-Calculator that we wish to merge to master and, presumably a PR on dropq that we wish to merge to master (making the change in dropq itself is trivial and would have to be done at some point in either case). All of the infrastructure we have in place for deployment presupposes we are deploying from master. For this case, though, we would have to deploy a test server that is synced to these pull requests. To me, it's seems clear that such an activity is time consuming and without purpose.

I'm not sure what the next steps should be. You seem opposed to merging 4 lines of code in to 700 line PR that breaks no tests, would save significant time, and would have zero user impact. We can schedule a code review of dropq if my explanation of the why the assertions should occur did not make sense.

**Comment by martinholmer** [comment]
T.J. @talumbau wrote:
> I don't understand your claims about the calculator function and your example shows desired behavior. The assertion violation you got is correct. example.py is a simple way of running dropq in the way that is done for the web application. In particular, we expect input from the user only for the year 2015. If somehow the web application was modified to provide a reform starting in 2016, and there were not concurrent changes made to dropq, this should be considered an error because it is unexpected input and it would be bad if the code did not raise an exception or trip an assertion.

OK, I stand corrected.  I have never used the webapp and had no idea that it was so severely limited in the range of reforms it can handle (that is, it "expect[s] input from the user only for the year 2015").  So, given what you say about the current design of the webapp, you are correct to say the code on the master branch works as designed.  But, nevertheless, that design of the webapp and its supporting code is virtually useless for real-world tax reform analysis.

This afternoon I have added three commits to pull request #343.  The first strengthens the checking of the reform dictionary passed to the Parameters implement_reform method.  The second fixes my revision of the calculator factory function so that it now supports dropq.run_models without changing any code in run_models.  And the third adds the test you recently suggested that shows the revised calculator factory function working as expected.

**Comment by talumbau** [comment]
Thanks for adding those commits and putting back in the test! This should allow a much smoother transition and easier deployment on my side. As a point of trivia, I misspoke somewhat above. The webapp supports reforms specified after 2015, but the first year must always be 2015 right now, so therefore the user_mods always looks like `{2015: {...} }`. We have discussed adding the feature to the webapp of allowing the user to choose which year to start a reform, but that interaction is not part of the web app right now.

**Comment by talumbau** [comment]
this is now resolved.

**Pull request closed without merging**
